import { pgTable, uuid, text, integer, timestamp, jsonb, primaryKey } from "drizzle-orm/pg-core";

// The V5 initial schema (ADR-0014, KAN-1223): exactly the four tables
// ADR-0014's "Schema sketch" names for this card -- `byok_keys` (ADR-0016)
// and `runs` are deliberately NOT defined here; they belong to KAN-1229/
// KAN-1231, which add their own migrations on top of this one later.
//
// This module only defines the schema-as-code; it is not wired into any
// route or the server's startup path (that's KAN-1224). It exists so
// `drizzle-kit generate` (see ../../drizzle.config.ts) has something to
// diff against to produce the SQL migration files checked into
// packages/server/drizzle/.
//
// Primary keys: `uuid`, generated by Postgres itself via `defaultRandom()`
// (`gen_random_uuid()`, built into Postgres's core since v13 -- no
// `pgcrypto`/`uuid-ossp` extension needed; confirmed empirically against
// the Postgres 18 image this schema is verified against, see this card's
// verification notes) rather than a `text` PK or a `serial`/`bigint` PK,
// because: (a) IDs are useful to generate client-side, before a row is
// ever inserted (`SpecRepository` callers, KAN-1224, will want an ID to
// hand back immediately); (b) sequential integer PKs leak row-count/
// creation-order information across what will be a public multi-tenant API
// with public signup (ADR-0013) -- not appropriate here; (c) keeping every
// table's own PK the same type as the `workspace_id`/`spec_id` foreign keys
// pointing at it keeps every FK column's type consistent across the whole
// schema. Every tenant-scoped table's `workspace_id` column exists now even
// though the RLS policies keying off it are a later card (KAN-1225) --
// ADR-0014 is explicit this is the pattern every such table follows.
//
// Every timestamp column is `timestamptz` (Drizzle's
// `{ withTimezone: true }`), never a naive timestamp, per this card's brief
// and standard Postgres hygiene.

export const workspaces = pgTable("workspaces", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const workspaceMembers = pgTable(
  "workspace_members",
  {
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    // No FK to a `users` table yet: Better Auth (ADR-0015) is what
    // introduces the users table, in a later card (KAN-1226). This column
    // exists now per ADR-0014's schema sketch; its FK gets added once that
    // table exists.
    userId: uuid("user_id").notNull(),
    // Placeholder text column -- KAN-1235's RBAC card (ADR-0017) defines
    // the real value set (e.g. "owner" | "admin" | "member"). V5 itself
    // only needs "member of this workspace or not" (ADR-0014), so this
    // card just needs the column to exist.
    role: text("role").notNull(),
  },
  (table) => [primaryKey({ columns: [table.workspaceId, table.userId] })],
);

export const specs = pgTable("specs", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => workspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  // The full, lossless AgentSpec YAML text (ADR-0002, ADR-0014's "does
  // ADR-0002 still hold, server-side?" answer). The database is a new
  // storage medium for the same YAML source of truth -- never a second,
  // parsed/parallel representation of a spec's content.
  yamlSource: text("yaml_source").notNull(),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const layouts = pgTable("layouts", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => workspaces.id, { onDelete: "cascade" }),
  specId: uuid("spec_id")
    .notNull()
    .references(() => specs.id, { onDelete: "cascade" }),
  // The sidecar .kampong/layout.json's hosted-mode equivalent (ADR-0006,
  // ADR-0014) -- `jsonb` (not plain `text`) since it's the queryable/
  // indexable Postgres JSON type and this card's brief asks for "sensible
  // Postgres types."
  layoutJson: jsonb("layout_json").notNull(),
});
