// Generates the exported project's Dockerfile + .dockerignore (KAN-1435,
// ADR-0022 "deployable = a container image" for the self-host path). No
// spec-derived values go into either -- both are the same for every export
// -- so unlike entry-point.ts/server-entry-point.ts these are plain
// constants, not functions of an AgentSpec.
//
// Two stages: `build` has devDependencies (typescript) to compile src/ ->
// dist/; the final `runtime` stage installs only production dependencies
// and copies the compiled output, so the shipped image doesn't carry
// TypeScript or tsx. The default command runs the webhook server
// (src/server.ts, compiled to dist/server.js) -- the live, deployable
// counterpart to the run-once `node dist/index.js` -- overridable per
// ADR-0022's "run the image with those env vars set" self-host path.

export function buildDockerfile(): string {
  return `# Generated by \`kampong export\`. One-way export -- see README.md.
# Two-stage build: compile with devDependencies, ship only the production
# dependencies + compiled output.

FROM node:22-slim AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:22-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json* ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist

# Connector/model \${ENV} tokens (e.g. -e SLACK_BOT_TOKEN=... -e ANTHROPIC_API_KEY=...)
# are supplied at \`docker run\` time -- never baked into the image.
EXPOSE 8080
CMD ["node", "dist/server.js"]
`;
}

export function buildDockerignore(): string {
  return [
    "node_modules/",
    "dist/",
    "*.tsbuildinfo",
    ".env",
    ".env.*",
    "!.env.example",
    ".git/",
    "",
  ].join("\n");
}
