import type { AgentSpec } from "@kampong/spec";

// Generates the exported project's runnable entry point (PLAN.md Shape S6,
// SLICES.md V4 KAN-1114). This is the one genuinely *generated* file in an
// export -- everything under templates/runtime/ is copied, not templated
// (ADR-0010) -- so it's kept small and easy to read: bake in the spec's
// concrete values as a plain literal, then drive the vendored `AgentRun`
// exactly the way `packages/cli/src/cli.ts`'s `run` command drives the real
// engine (start() / loop while "awaiting_approval" / resume()), adapted to a
// plain stdin prompt with no `@kampong/cli` dependency (ADR-0002).

/**
 * Makes a spec-derived string safe to interpolate into a generated `//`
 * line comment. `spec.agent.id` (and every other free-text spec field) is
 * only constrained by the schema to `z.string().min(1)`
 * (packages/spec/src/schema.ts) -- no character restriction -- and
 * hand-authored/externally-generated specs are a first-class,
 * untrusted-until-validated input here (AGENTS.md, ADR-0008), not an edge
 * case. A `//` comment only runs to the next line terminator, and
 * JavaScript recognizes more of those than plain LF/CR: the Unicode LINE
 * SEPARATOR and PARAGRAPH SEPARATOR code points (0x2028/0x2029) end a `//`
 * comment too. Without this, a spec whose `agent.id` contained one of
 * those characters followed by arbitrary JS would break out of the
 * comment and become live, executable top-level code in the generated
 * project -- `npm start` on that exported project would run it. Every
 * control character (all four line terminators included) is replaced
 * with a single space, so the value can never introduce a new line inside
 * the single-line comment it's placed in. Walks code points (rather than
 * a regex character class) to sidestep any ambiguity around embedding raw
 * control code points in a regex literal.
 */
function sanitizeForLineComment(value: string): string {
  return Array.from(value)
    .map((ch) => {
      const code = ch.codePointAt(0)!;
      const isC0OrDel = code <= 0x1f || code === 0x7f;
      const isUnicodeLineTerminator = code === 0x2028 || code === 0x2029;
      return isC0OrDel || isUnicodeLineTerminator ? " " : ch;
    })
    .join("");
}

export function buildEntryPointSource(spec: AgentSpec): string {
  const specLiteral = JSON.stringify(spec, null, 2);
  const safeAgentId = sanitizeForLineComment(spec.agent.id);

  return `#!/usr/bin/env node
// Generated by \`kampong export\` from the spec "${safeAgentId}". One-way
// export -- see README.md and docs/adr/0002 / docs/adr/0010 in the
// originating repo. This file, and everything under src/runtime/, is your
// own code from here on: no dependency on Kampong Agents, and it will not
// be regenerated or touched by a future export of the same spec.

import { createInterface } from "node:readline/promises";
import { createAgentRun } from "./runtime/run.js";
import type { AgentSpec } from "./runtime/spec-types.js";
import type { RunState } from "./runtime/run.js";

// The spec this project was exported from, baked in as a plain literal --
// already validated at export time, so it is never re-parsed or
// re-validated here.
const SPEC: AgentSpec = ${specLiteral};

interface CliArgs {
  input: string;
  approveAll: boolean;
  json: boolean;
}

const DEFAULT_INPUT = "Run this agent.";

function parseArgs(argv: string[]): CliArgs {
  let input = DEFAULT_INPUT;
  let approveAll = false;
  let json = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--input") {
      input = argv[++i] ?? input;
    } else if (arg === "--approve-all") {
      approveAll = true;
    } else if (arg === "--json") {
      json = true;
    }
  }
  return { input, approveAll, json };
}

/**
 * Mirrors \`kampong run\`'s stdin approval prompt (packages/cli/src/cli.ts
 * in the originating repo), adapted to write directly to process.stdout/
 * stderr instead of an injectable CliIO -- this project has no test-harness
 * reason to abstract that away.
 */
async function promptApproval(
  state: RunState,
  approveAll: boolean,
  json: boolean,
): Promise<{ approved: boolean; reason?: string }> {
  const pending = state.pendingApproval;
  if (!pending) return { approved: approveAll };

  if (approveAll) {
    // Always stderr: --json promises exactly one JSON object on stdout.
    process.stderr.write(
      \`[--approve-all] auto-approving "\${pending.step}" (\${pending.kind}): \${pending.reason}\\n\`,
    );
    return { approved: true };
  }

  const rl = createInterface({
    input: process.stdin,
    output: json ? process.stderr : process.stdout,
  });
  try {
    const answer = await rl.question(
      \`\\nApproval required at step "\${pending.step}" (\${pending.kind}): \${pending.reason}\\nApprove? [y/N]: \`,
    );
    const approved = /^y(es)?$/i.test(answer.trim());
    let reason: string | undefined;
    if (!approved) {
      reason = (await rl.question("Reason for rejection (optional): ")).trim() || undefined;
    }
    return { approved, reason };
  } finally {
    rl.close();
  }
}

/**
 * The three terminal branches below (thrown error, "completed",
 * "rejected"/"failed") all boil down to the same shape: one JSON object on
 * stdout for \`--json\`, or a couple of human-readable lines otherwise --
 * only the payload and the stream (stdout for success, stderr for failure)
 * differ. Centralizing that here keeps each branch a one-call description
 * of *what* it reports rather than *how* to report it.
 */
function emitResult(
  json: boolean,
  payload: Record<string, unknown>,
  textLines: string[],
  stream: "stdout" | "stderr",
): void {
  if (json) {
    console.log(JSON.stringify(payload));
    return;
  }
  const write = stream === "stdout" ? console.log : console.error;
  for (const line of textLines) write(line);
}

function reportFailure(err: unknown, json: boolean): void {
  const message = err instanceof Error ? err.message : String(err);
  emitResult(
    json,
    { success: false, phase: "execution", error: message },
    [\`Execution failed: \${message}\`],
    "stderr",
  );
}

async function main(): Promise<void> {
  const { input, approveAll, json } = parseArgs(process.argv.slice(2));

  let run: ReturnType<typeof createAgentRun>;
  try {
    run = createAgentRun(SPEC);
  } catch (err) {
    reportFailure(err, json);
    process.exitCode = 2;
    return;
  }

  let state: RunState;
  try {
    state = await run.start(input);
    while (state.status === "awaiting_approval") {
      const decision = await promptApproval(state, approveAll, json);
      state = await run.resume(decision.approved, decision.reason);
    }
  } catch (err) {
    reportFailure(err, json);
    process.exitCode = 2;
    return;
  }

  if (state.status === "completed") {
    emitResult(
      json,
      { success: true, status: state.status, output: state.finalOutput, trace: state.trace },
      ["Run completed.", JSON.stringify(state.finalOutput, null, 2)],
      "stdout",
    );
    return;
  }

  // state.status is "rejected" or "failed" here -- the loop above only
  // exits once status leaves "awaiting_approval", and start()/resume() only
  // ever settle on a terminal or paused state.
  emitResult(
    json,
    { success: false, status: state.status, error: state.error, trace: state.trace },
    [\`Run \${state.status}: \${state.error ?? "(no error message)"}\`],
    "stderr",
  );
  process.exitCode = 2;
}

main().catch((err: unknown) => {
  process.stderr.write(
    \`unexpected error: \${err instanceof Error ? (err.stack ?? err.message) : String(err)}\\n\`,
  );
  process.exitCode = 2;
});
`;
}
