import { permissionsOf, serializeLockfile, type AgentSpec } from "@kampong/spec";
import { fileHashes, refOf, type ExportComponent } from "./components.js";
import { slugifyPackageName } from "./package-json.js";

// The records an export leaves so a user can check what they hold (KAN-1837, ADR-0010): `kampong.lock`
// (the digest and permissions each component was exported as, the same file `kampong lock` writes) and
// `sbom.json` (a CycloneDX bill of materials with every file's hash). An export cannot be revoked
// remotely, so the check is user-side: `npm run verify` re-hashes components/ against sbom.json, and the
// project does the same against the baked digests every time it starts.

export function buildLockfileText(components: ExportComponent[]): string {
  return serializeLockfile({
    version: 1,
    components: Object.fromEntries(
      components.map((c) => [
        refOf(c),
        { digest: c.digest, permissions: permissionsOf(c.manifest) },
      ]),
    ),
  });
}

const purlOf = (name: string, version: string): string =>
  `pkg:npm/${name.replace(/^@/, "%40")}@${version}`;

/** CycloneDX 1.5. No timestamp or serial number, so exporting the same spec twice gives the same bytes. */
export function buildSbom(spec: AgentSpec, components: ExportComponent[]): string {
  const deps = new Map<string, { name: string; version: string }>();
  for (const { manifest } of components) {
    if (manifest.kind !== "module") continue;
    for (const [name, version] of Object.entries(manifest.deps ?? {}))
      deps.set(name, { name, version });
  }
  const bom = {
    bomFormat: "CycloneDX",
    specVersion: "1.5",
    version: 1,
    metadata: {
      component: { type: "application", name: slugifyPackageName(spec.agent.id), version: "0.1.0" },
    },
    components: [
      ...components.map((c) => ({
        type: "library",
        "bom-ref": refOf(c),
        name: c.manifest.id,
        version: c.manifest.version,
        properties: [
          { name: "kampong:digest", value: c.digest },
          { name: "kampong:kind", value: c.manifest.kind },
        ],
        components: Object.entries(fileHashes(c.files)).map(([path, hash]) => ({
          type: "file",
          name: path,
          hashes: [{ alg: "SHA-256", content: hash }],
        })),
      })),
      ...[...deps.values()]
        .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
        .map(({ name, version }) => ({
          type: "library",
          "bom-ref": purlOf(name, version),
          name,
          version,
          purl: purlOf(name, version),
        })),
    ],
  };
  return `${JSON.stringify(bom, null, 2)}\n`;
}

/** `src/verify.ts`: checks components/ against sbom.json, a record independent of the digests baked into the code. */
export function buildVerifyEntryPointSource(): string {
  return `// Generated by \`kampong export\`. \`npm run verify\` re-hashes components/ against sbom.json, the
// record written at export time, and exits non-zero if anything differs. The project also checks the
// same files against the digests baked into src/components.generated.ts every time it starts.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ComponentVerificationError, verifyComponents, type ExpectedComponent } from "./runtime/component-verify.js";

// sbom.json and components/ sit at the project root, one level above both src/ and dist/.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

interface SbomComponent {
  name: string;
  version: string;
  properties?: { name: string; value: string }[];
  components?: { name: string; hashes?: { content: string }[] }[];
}

let sbom: { components?: SbomComponent[] };
try {
  sbom = JSON.parse(readFileSync(join(ROOT, "sbom.json"), "utf8"));
} catch (err) {
  console.error(\`sbom.json cannot be read: \${(err as Error).message}\`);
  process.exit(1);
}
const expected: ExpectedComponent[] = [];
for (const c of sbom.components ?? []) {
  const digest = c.properties?.find((p) => p.name === "kampong:digest")?.value;
  if (digest === undefined) continue; // an npm dependency, pinned by package.json
  expected.push({
    ref: \`\${c.name}@\${c.version}\`,
    digest,
    path: \`\${c.name}/\${c.version}\`,
    files: Object.fromEntries((c.components ?? []).map((f) => [f.name, f.hashes?.[0]?.content ?? ""])),
  });
}

if (expected.length === 0) {
  console.error("sbom.json lists no components: it is not the record this project was exported with.");
  process.exit(1);
}
try {
  await verifyComponents(expected, join(ROOT, "components"));
  console.log(\`Verified \${expected.length} component(s) against sbom.json.\`);
} catch (err) {
  console.error(err instanceof ComponentVerificationError ? err.message : err);
  process.exit(1);
}
`;
}
