import type { AgentSpec } from "@kampong/spec";

// Generates the exported project's live-webhook server entry (KAN-1435,
// ADR-0021/ADR-0022 "Slice C2"): the deployable counterpart to
// entry-point.ts's run-once CLI. Like that file, this is a genuinely
// *generated* file (the spec is baked in as a plain literal), not a copy
// under templates/runtime/ (ADR-0010) -- it adapts
// packages/cli/src/serve-server.ts's routes plus the `.listen()` call from
// packages/cli/src/cli.ts's `runServeCommand`, dropping the file-path
// parsing (the spec is already validated and baked in at export time, same
// reasoning as entry-point.ts) and the `RunManager` test seams (a real
// deploy needs none of them).

/** Shared with entry-point.ts's sanitizeForLineComment -- see that file for why this is needed for any spec-derived value placed in a generated `//` line comment. */
function sanitizeForLineComment(value: string): string {
  return Array.from(value)
    .map((ch) => {
      const code = ch.codePointAt(0)!;
      const isC0OrDel = code <= 0x1f || code === 0x7f;
      const isUnicodeLineTerminator = code === 0x2028 || code === 0x2029;
      return isC0OrDel || isUnicodeLineTerminator ? " " : ch;
    })
    .join("");
}

export function buildServerEntryPointSource(spec: AgentSpec): string {
  const specLiteral = JSON.stringify(spec, null, 2);
  const safeAgentId = sanitizeForLineComment(spec.agent.id);

  return `#!/usr/bin/env node
// Generated by \`kampong export\` from the spec "${safeAgentId}". One-way
// export -- see README.md and docs/adr/0002 / docs/adr/0010 / docs/adr/0021 /
// docs/adr/0022 in the originating repo. This file, and everything under
// src/runtime/, is your own code from here on: no dependency on Kampong
// Agents, and it will not be regenerated or touched by a future export of
// the same spec.
//
// This is the live, triggerable counterpart to src/index.ts's run-once CLI
// (ADR-0021/ADR-0022): the process stays up and starts one run per incoming
// POST /webhook, mirroring \`kampong serve\`. Deploying is "run this process
// with the connector/model \${ENV} tokens set" -- see the generated
// Dockerfile for the container form of that. Execution is on-demand: a
// webhook event drives one run on this shared process, there is no
// always-on per-workflow worker.

import Fastify from "fastify";
import { RunManager } from "./runtime/run-manager.js";
import type { RunEvent } from "./runtime/workflow.js";
import type { AgentSpec } from "./runtime/spec-types.js";

// The spec this project was exported from, baked in as a plain literal --
// already validated at export time, so it is never re-parsed or
// re-validated here.
const SPEC: AgentSpec = ${specLiteral};

const PORT = Number(process.env.PORT ?? 8080);
const HOST = process.env.HOST ?? "0.0.0.0";

const app = Fastify({ logger: false });
const runManager = new RunManager();

// Accept any non-JSON content type as a raw string body, so \`curl -d "..."\`
// (which defaults to urlencoded) and text/plain both work; JSON bodies keep
// Fastify's built-in object parsing.
app.addContentTypeParser("*", { parseAs: "string" }, (_req, body, done) => done(null, body));

// POST /webhook -- the trigger. The request body becomes the run input (raw
// string as-is; a JSON body is passed through as its JSON text). Returns the
// run id immediately (on-demand execution); the caller polls /runs/:id or
// streams /runs/:id/events and resolves approvals via /runs/:id/approve.
app.post("/webhook", async (request, reply) => {
  const input = typeof request.body === "string" ? request.body : JSON.stringify(request.body);
  const { id, state } = await runManager.start(SPEC, input);
  return reply.code(201).send({ success: true, id, state });
});

app.get<{ Params: { id: string } }>("/runs/:id", async (request, reply) => {
  const run = runManager.get(request.params.id);
  if (!run) {
    return reply
      .code(404)
      .send({ success: false, error: \`Unknown run id "\${request.params.id}".\` });
  }
  return { success: true, state: run.getState() };
});

app.post<{ Params: { id: string }; Body: { approved?: boolean; reason?: string } }>(
  "/runs/:id/approve",
  async (request, reply) => {
    const { approved, reason } = request.body ?? {};
    if (typeof approved !== "boolean") {
      return reply.code(400).send({ success: false, error: "\`approved\` (a boolean) is required." });
    }
    try {
      const state = await runManager.approve(request.params.id, approved, reason);
      if (state === undefined) {
        return reply
          .code(404)
          .send({ success: false, error: \`Unknown run id "\${request.params.id}".\` });
      }
      return { success: true, state };
    } catch (err) {
      return reply.code(409).send({ success: false, error: (err as Error).message });
    }
  },
);

app.get<{ Params: { id: string } }>("/runs/:id/events", (request, reply) => {
  const run = runManager.get(request.params.id);
  if (!run) {
    reply.code(404).send({ success: false, error: \`Unknown run id "\${request.params.id}".\` });
    return;
  }
  reply.hijack();
  reply.raw.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
  });
  reply.raw.write(\`data: \${JSON.stringify({ type: "state", state: run.getState() })}\\n\\n\`);
  const onEvent = (event: RunEvent) => {
    reply.raw.write(
      \`data: \${JSON.stringify({ type: "event", event, state: run.getState() })}\\n\\n\`,
    );
  };
  run.on("event", onEvent);
  request.raw.on("close", () => run.off("event", onEvent));
});

app.get("/healthz", async () => ({ status: "ok" }));

app
  .listen({ port: PORT, host: HOST })
  .then(() => {
    console.log(\`listening at http://\${HOST}:\${PORT}\`);
  })
  .catch((err: unknown) => {
    console.error("failed to start:", err);
    process.exitCode = 1;
  });
`;
}
