import { z } from "zod";
import { LineCounter, parseDocument, stringify } from "yaml";
import { toSpecError, type SpecError } from "./parse.js";
import { componentIdSchema, exactVersionSchema } from "./component.js";

// kampong.lock (KAN-1834, ADR-0025 and ADR-0026): pins each `id@version` a project uses to the content
// digest of the component it was reviewed as. There are no tags or ranges, so a component cannot
// change underneath a spec; changing a pinned digest is an explicit, visible act (`kampong lock --update`).

export const LOCKFILE_NAME = "kampong.lock";
export const LOCKFILE_VERSION = 1;

const DIGEST = /^sha256:[0-9a-f]{64}$/;

// An id@version key. Split and checked with the same schemas a manifest and a spec use.
const lockKeySchema = z.string().superRefine((key, ctx) => {
  const at = key.lastIndexOf("@");
  const id = at < 0 ? "" : key.slice(0, at);
  const version = at < 0 ? "" : key.slice(at + 1);
  if (!componentIdSchema.safeParse(id).success || !exactVersionSchema.safeParse(version).success) {
    ctx.addIssue({ code: "custom", message: 'must be an exact "namespace/name@1.2.3"' });
  }
});

export const lockfileSchema = z
  .object({
    version: z.literal(LOCKFILE_VERSION),
    components: z.record(
      lockKeySchema,
      z
        .object({ digest: z.string().regex(DIGEST, "must be sha256:<64 lower-case hex digits>") })
        .strict(),
    ),
  })
  .strict();

export type Lockfile = z.infer<typeof lockfileSchema>;

export interface LockfileParseResult {
  success: boolean;
  lockfile?: Lockfile;
  errors: SpecError[];
}

export function parseLockfile(source: string): LockfileParseResult {
  const lineCounter = new LineCounter();
  const doc = parseDocument(source, { lineCounter });
  if (doc.errors.length > 0) {
    return {
      success: false,
      errors: doc.errors.map((err) => ({
        path: [],
        message: err.message,
        line: err.linePos?.[0]?.line,
        column: err.linePos?.[0]?.col,
      })),
    };
  }
  const result = lockfileSchema.safeParse(doc.toJS({ maxAliasCount: 0 }));
  if (!result.success) {
    return {
      success: false,
      errors: result.error.issues.map((issue) => toSpecError(issue, doc, lineCounter)),
    };
  }
  // A null-prototype copy is not needed for reads (callers use Object.hasOwn), but the parsed
  // object is rebuilt from own keys only so nothing inherited can ride along.
  const components: Lockfile["components"] = Object.create(null) as Lockfile["components"];
  for (const key of Object.keys(result.data.components)) {
    components[key] = { digest: result.data.components[key]!.digest };
  }
  return { success: true, lockfile: { version: LOCKFILE_VERSION, components }, errors: [] };
}

/** Deterministic text: keys sorted, one entry per component, so a lockfile diff shows exactly what changed. */
export function serializeLockfile(lockfile: Lockfile): string {
  const keys = Object.keys(lockfile.components).sort();
  const components: Record<string, { digest: string }> = {};
  for (const key of keys) components[key] = { digest: lockfile.components[key]!.digest };
  const header =
    "# Generated by `kampong lock`. Pins each component to the digest it was reviewed as.\n" +
    "# Review any change to this file like a dependency update.\n";
  return header + stringify({ version: LOCKFILE_VERSION, components }, { lineWidth: 0 });
}
