import { describe, expect, it } from "vitest";
import { getTableName } from "drizzle-orm";
import { getTableConfig, type PgColumn } from "drizzle-orm/pg-core";
import {
  workspaces,
  workspaceMembers,
  specs,
  layouts,
  user,
  session,
  account,
  verification,
  invitation,
  ssoProvider,
} from "../../../src/db/schema.js";

// KAN-1223 (ADR-0014's schema sketch, this card's narrow scope): originally
// exactly the four tables `workspaces`, `workspace_members`, `specs`,
// `layouts` -- deliberately NOT `byok_keys` or `runs` (those are
// KAN-1229/KAN-1231's own migrations). KAN-1226 (ADR-0015) added Better
// Auth's own tables plus additive columns on `workspaces`/
// `workspace_members` -- see those describe blocks below. No live Postgres
// is needed for any of this: Drizzle's schema-as-code objects carry their
// own introspectable table/column/constraint metadata (`getTableConfig`),
// so this is a true no-infra unit test, not a stand-in for the
// live-Postgres verification this card's report documents separately.

function columnNames(table: Parameters<typeof getTableConfig>[0]): string[] {
  return getTableConfig(table).columns.map((c) => c.name);
}

function column(table: Parameters<typeof getTableConfig>[0], name: string): PgColumn | undefined {
  return getTableConfig(table).columns.find((c) => c.name === name);
}

describe("workspaces table", () => {
  it("is named 'workspaces' with the expected columns", () => {
    expect(getTableName(workspaces)).toBe("workspaces");
    expect(columnNames(workspaces)).toEqual([
      "id",
      "name",
      "slug",
      "logo",
      "metadata",
      "created_at",
      "member_count",
    ]);
  });

  it("has a uuid primary key generated by the database, and no foreign keys", () => {
    const id = column(workspaces, "id");
    expect(id?.primary).toBe(true);
    expect(id?.columnType).toBe("PgUUID");
    expect(id?.hasDefault).toBe(true);
    expect(getTableConfig(workspaces).foreignKeys).toHaveLength(0);
  });

  it("requires name and stores created_at as a not-null timestamptz with a default", () => {
    expect(column(workspaces, "name")?.notNull).toBe(true);
    const createdAt = column(workspaces, "created_at");
    expect(createdAt?.columnType).toBe("PgTimestamp");
    expect(createdAt?.notNull).toBe(true);
    expect(createdAt?.hasDefault).toBe(true);
  });

  it("KAN-1226: requires a unique slug (Better Auth's organization plugin default field), leaves logo/metadata nullable", () => {
    const slug = column(workspaces, "slug");
    expect(slug?.notNull).toBe(true);
    expect(slug?.isUnique).toBeTruthy();
    expect(column(workspaces, "logo")?.notNull).toBe(false);
    expect(column(workspaces, "metadata")?.notNull).toBe(false);
  });

  it("KAN-1226: defaults member_count to 0 -- maintained by a trigger (drizzle/0004_*.sql), never written directly", () => {
    const memberCount = column(workspaces, "member_count");
    expect(memberCount?.columnType).toBe("PgInteger");
    expect(memberCount?.notNull).toBe(true);
    expect(memberCount?.hasDefault).toBe(true);
  });
});

describe("workspace_members table", () => {
  it("is named 'workspace_members' with the expected columns", () => {
    expect(getTableName(workspaceMembers)).toBe("workspace_members");
    expect(columnNames(workspaceMembers)).toEqual([
      "workspace_id",
      "user_id",
      "role",
      "id",
      "created_at",
    ]);
  });

  it("has a composite primary key on (workspace_id, user_id)", () => {
    const [pk] = getTableConfig(workspaceMembers).primaryKeys;
    expect(pk?.columns.map((c) => c.name)).toEqual(["workspace_id", "user_id"]);
  });

  it("has workspace_id and user_id as cascading foreign keys into workspaces.id / user.id", () => {
    const fks = getTableConfig(workspaceMembers).foreignKeys;
    expect(fks).toHaveLength(2);

    const byForeignTable = new Map(
      fks.map((fk) => {
        const ref = fk.reference();
        return [getTableName(ref.foreignTable), { fk, ref }];
      }),
    );

    const workspaceFk = byForeignTable.get("workspaces");
    expect(workspaceFk?.ref.columns.map((c) => c.name)).toEqual(["workspace_id"]);
    expect(workspaceFk?.ref.foreignColumns.map((c) => c.name)).toEqual(["id"]);
    expect(workspaceFk?.fk.onDelete).toBe("cascade");

    const userFk = byForeignTable.get("user");
    expect(userFk?.ref.columns.map((c) => c.name)).toEqual(["user_id"]);
    expect(userFk?.ref.foreignColumns.map((c) => c.name)).toEqual(["id"]);
    expect(userFk?.fk.onDelete).toBe("cascade");
  });

  it("has a not-null user_id and role placeholder column, neither with a default", () => {
    expect(column(workspaceMembers, "user_id")?.notNull).toBe(true);
    const role = column(workspaceMembers, "role");
    expect(role?.columnType).toBe("PgText");
    expect(role?.notNull).toBe(true);
  });

  it("KAN-1226: has a unique, database-generated id and a defaulted created_at -- Better Auth's `member` model's own required fields", () => {
    const id = column(workspaceMembers, "id");
    expect(id?.columnType).toBe("PgUUID");
    expect(id?.notNull).toBe(true);
    expect(id?.hasDefault).toBe(true);
    expect(id?.isUnique).toBeTruthy();

    const createdAt = column(workspaceMembers, "created_at");
    expect(createdAt?.notNull).toBe(true);
    expect(createdAt?.hasDefault).toBe(true);
  });
});

describe("Better Auth's own tables (KAN-1226, ADR-0015)", () => {
  it("user: has a uuid pk, unique email, and boolean emailVerified defaulting to false", () => {
    expect(getTableName(user)).toBe("user");
    expect(column(user, "id")?.columnType).toBe("PgUUID");
    expect(column(user, "email")?.isUnique).toBeTruthy();
    const emailVerified = column(user, "email_verified");
    expect(emailVerified?.columnType).toBe("PgBoolean");
    expect(emailVerified?.notNull).toBe(true);
    expect(emailVerified?.hasDefault).toBe(true);
  });

  it("session: has a unique token, a cascading FK to user.id, and a set-null FK to workspaces.id (activeOrganizationId)", () => {
    expect(getTableName(session)).toBe("session");
    expect(column(session, "token")?.isUnique).toBeTruthy();

    const fks = getTableConfig(session).foreignKeys;
    const byForeignTable = new Map(
      fks.map((fk) => [getTableName(fk.reference().foreignTable), fk]),
    );
    expect(byForeignTable.get("user")?.onDelete).toBe("cascade");
    expect(byForeignTable.get("workspaces")?.onDelete).toBe("set null");
  });

  it("account: stores a password hash or OAuth tokens, cascading FK to user.id", () => {
    expect(getTableName(account)).toBe("account");
    expect(column(account, "password")?.notNull).toBe(false);
    expect(column(account, "access_token")?.notNull).toBe(false);
    const [fk] = getTableConfig(account).foreignKeys;
    expect(fk?.onDelete).toBe("cascade");
  });

  it("verification: no foreign keys, all Better Auth default fields present", () => {
    expect(getTableName(verification)).toBe("verification");
    expect(columnNames(verification)).toEqual([
      "id",
      "identifier",
      "value",
      "expires_at",
      "created_at",
      "updated_at",
    ]);
  });

  it("invitation: cascading FK to workspaces.id (organizationId, remapped table only, not field name)", () => {
    expect(getTableName(invitation)).toBe("invitation");
    const fks = getTableConfig(invitation).foreignKeys;
    const byForeignTable = new Map(
      fks.map((fk) => [getTableName(fk.reference().foreignTable), fk]),
    );
    expect(byForeignTable.get("workspaces")?.onDelete).toBe("cascade");
    expect(byForeignTable.has("user")).toBe(true);
  });

  it("sso_provider: adopted dormant (ADR-0015) -- table exists with a unique providerId, no row ever written by this card", () => {
    expect(getTableName(ssoProvider)).toBe("sso_provider");
    expect(column(ssoProvider, "provider_id")?.isUnique).toBeTruthy();
  });
});

describe("specs table", () => {
  it("is named 'specs' with the expected columns", () => {
    expect(getTableName(specs)).toBe("specs");
    expect(columnNames(specs)).toEqual([
      "id",
      "workspace_id",
      "name",
      "yaml_source",
      "version",
      "created_at",
      "updated_at",
    ]);
  });

  it("has a uuid primary key and a cascading foreign key into workspaces.id", () => {
    expect(column(specs, "id")?.primary).toBe(true);
    const [fk] = getTableConfig(specs).foreignKeys;
    const ref = fk?.reference();
    expect(ref?.columns.map((c) => c.name)).toEqual(["workspace_id"]);
    expect(ref && getTableName(ref.foreignTable)).toBe("workspaces");
    expect(fk?.onDelete).toBe("cascade");
  });

  it("stores yaml_source as not-null text (the lossless YAML, per ADR-0002/ADR-0014)", () => {
    const yamlSource = column(specs, "yaml_source");
    expect(yamlSource?.columnType).toBe("PgText");
    expect(yamlSource?.notNull).toBe(true);
  });

  it("defaults version to 1 and both timestamps to now(), all not-null", () => {
    const version = column(specs, "version");
    expect(version?.columnType).toBe("PgInteger");
    expect(version?.notNull).toBe(true);
    expect(version?.hasDefault).toBe(true);

    for (const name of ["created_at", "updated_at"]) {
      const col = column(specs, name);
      expect(col?.columnType).toBe("PgTimestamp");
      expect(col?.notNull).toBe(true);
      expect(col?.hasDefault).toBe(true);
    }
  });
});

describe("layouts table", () => {
  it("is named 'layouts' with the expected columns", () => {
    expect(getTableName(layouts)).toBe("layouts");
    expect(columnNames(layouts)).toEqual(["id", "workspace_id", "spec_id", "layout_json"]);
  });

  it("has a uuid primary key and cascading foreign keys into workspaces.id and specs.id", () => {
    expect(column(layouts, "id")?.primary).toBe(true);

    const fks = getTableConfig(layouts).foreignKeys;
    expect(fks).toHaveLength(2);

    const byForeignTable = new Map(
      fks.map((fk) => {
        const ref = fk.reference();
        return [getTableName(ref.foreignTable), { fk, ref }];
      }),
    );

    const workspaceFk = byForeignTable.get("workspaces");
    expect(workspaceFk?.ref.columns.map((c) => c.name)).toEqual(["workspace_id"]);
    expect(workspaceFk?.ref.foreignColumns.map((c) => c.name)).toEqual(["id"]);
    expect(workspaceFk?.fk.onDelete).toBe("cascade");

    const specFk = byForeignTable.get("specs");
    expect(specFk?.ref.columns.map((c) => c.name)).toEqual(["spec_id"]);
    expect(specFk?.ref.foreignColumns.map((c) => c.name)).toEqual(["id"]);
    expect(specFk?.fk.onDelete).toBe("cascade");
  });

  it("stores layout_json as not-null jsonb", () => {
    const layoutJson = column(layouts, "layout_json");
    expect(layoutJson?.columnType).toBe("PgJsonb");
    expect(layoutJson?.notNull).toBe(true);
  });
});

describe("scope discipline (KAN-1223 vs later cards)", () => {
  it("does not export a byok_keys or runs table -- those are KAN-1229/KAN-1231's own migrations", async () => {
    const schemaModule = await import("../../../src/db/schema.js");
    const exportedNames = Object.keys(schemaModule);
    expect(exportedNames).not.toContain("byokKeys");
    expect(exportedNames).not.toContain("runs");
  });
});
